create table `personas` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(100) not null, `email` varchar(100) not null, `telefono` varchar(50) null, `cedula` varchar(50) null, `observaciones` varchar(200) null, `password` varchar(200) not null, `avatar` varchar(200) null, `last_login` timestamp null, `residencia_id` bigint null, `admin` tinyint(1) not null default '0', `remember_token` varchar(100) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `personas` add unique personas_email_unique(`email`)
create table `noticias` (`id` int unsigned not null auto_increment primary key, `titulo` varchar(50) not null, `contenido` text not null, `persona` varchar(200) null, `user_id` int null, `fecha` date null, `media` varchar(200) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `eventos` (`id` int unsigned not null auto_increment primary key, `razon` varchar(50) not null, `fecha_ini` date not null, `fecha_fin` date not null, `tiempo_ini` time not null, `tiempo_fin` time not null, `persona` varchar(50) null, `user_id` int null, `areas` varchar(200) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `residencias` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `solvencia` tinyint(1) null default '0', `cant_personas` bigint null, `persona_id_propietario` bigint null, `alicuota` decimal(8, 2) not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `residencias` add unique residencias_nombre_unique(`nombre`)
create table `directiva` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `email` varchar(255) not null, `telefono` varchar(255) not null, `cargo` varchar(255) not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `areas` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `descripcion` varchar(500) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `areas` add unique areas_nombre_unique(`nombre`)
create table `facturas` (`id` int unsigned not null auto_increment primary key, `mes` int not null, `año` int not null, `residencia_id` bigint null, `porcentual` tinyint(1) null default '1', `categoria` varchar(50) null, `monto` decimal(20, 3) not null, `concepto` varchar(50) not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `recibos` (`id` int unsigned not null auto_increment primary key, `concepto` varchar(50) not null, `monto` decimal(20, 3) not null, `persona_id` bigint not null, `transaccion` varchar(50) not null, `path` varchar(200) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `personal` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(100) not null, `cedula` varchar(50) null, `telefono` varchar(50) null, `email` varchar(50) null, `cargo` varchar(200) null, `residencia_id` bigint not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `encuestas` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(100) not null, `pregunta` varchar(255) not null, `respuesta1` varchar(255) null, `respuesta2` varchar(255) null, `respuesta3` varchar(255) null, `respuesta4` varchar(255) null, `respuesta5` varchar(255) null, `respuesta6` varchar(255) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `encuestas_respuestas` (`id` int unsigned not null auto_increment primary key, `respuesta` bigint not null, `encuesta_id` bigint not null, `persona_id` bigint not null, `comentarios` varchar(500) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `portadas` (`id` int unsigned not null auto_increment primary key, `titulo` varchar(50) null, `contenido` varchar(500) null, `media` varchar(200) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `solvencia` (`id` int unsigned not null auto_increment primary key, `residencia_id` bigint not null, `mes` int not null, `año` int not null, `monto` decimal(20, 3) not null, `facturado_el` timestamp default 0 not null, `cancelado_el` timestamp default 0 not null, `estado` int not null default '0', `descripcion` varchar(50) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `galeria` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(300) not null, `persona_id` bigint not null, `path` varchar(100) not null, `album` varchar(50) not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `vehiculos` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(255) not null, `color` varchar(255) not null, `placa` varchar(255) not null, `residencia_id` int not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `visitantes` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(255) not null, `cedula` varchar(255) not null, `telefono` varchar(255) null, `email` varchar(255) null, `residencia_id` int not null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
create table `documentos` (`id` int unsigned not null auto_increment primary key, `titulo` varchar(255) not null, `contenido` text not null, `activo` tinyint(1) not null default '1', `morosos` tinyint(1) not null default '1', `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `documentos` add unique documentos_titulo_unique(`titulo`)
create table `dispositivos` (`id` int unsigned not null auto_increment primary key, `token` varchar(255) not null, `dispositivo` varchar(255) null, `plataforma` varchar(255) not null default 'android', `user_id` int null, `active` tinyint(1) not null default '1', `noticias_enabled` tinyint(1) not null default '1', `eventos_enabled` tinyint(1) not null default '1', `mensajes_enabled` tinyint(1) not null default '1', `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `dispositivos` add unique dispositivos_token_unique(`token`)
create table `password_reminders` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci
alter table `password_reminders` add index password_reminders_email_index(`email`)
alter table `password_reminders` add index password_reminders_token_index(`token`)
